<a href="https://colab.research.google.com/github/InowaR/map/blob/main/find_path.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
a = np.array([[0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]])
reshape = a.reshape(6,6)
print(reshape)

vector = np.ravel(a)

row = []
count = 0
for i in vector:
  if i == 1:
    row.append(count)
  count +=1
print(row, "row indexes")

arr = []
i = 0
while i < 6:
  arr.append(a[:,i])
  i += 1

col = np.ravel(arr)


column = []
count = 0
for j in col:
  if j == 1:
    column.append(count)
  count += 1
print(column, "column indexes")

b = np.zeros(36)
i = 0
while i < 10:   # number of ones
  b[i] += 1
  i += 1
np.random.shuffle(b)
b = b.reshape(6,6)
print(b)

[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[8, 9, 14, 15, 20, 21] row indexes
[13, 14, 15, 19, 20, 21] column indexes
[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0.]]
