<a href="https://colab.research.google.com/github/InowaR/map/blob/main/find_path.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
a = np.array([[0, 0, 0, 0, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 1, 1, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]])
reshape = a.reshape(6,6)
print(reshape)
vector = np.ravel(a)
row = []
count = 0
for i in vector:
  if i == 1:
    row.append(count)
  count +=1
print(row, "row indexes")
b = np.zeros(36)
i = 0
while i < 11:   # path numbers
  b[i] += 2
  i += 1
np.random.shuffle(b)
for i in row:
  b[i] = 1
b = b.reshape(6,6)
print(b)

[[0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[8, 9, 14, 15, 20, 21] row indexes
[[0. 0. 2. 0. 0. 0.]
 [0. 2. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0. 2.]
 [0. 0. 1. 1. 2. 2.]
 [2. 2. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 2.]]
