<a href="https://colab.research.google.com/github/InowaR/map/blob/main/generator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [229]:
import numpy as np
from google.colab import output

while True:
  try:
    b = np.zeros(100)
    i = 0
    while i < 40:   # number of ones
      b[i] += 1
      i += 1
    np.random.shuffle(b)
    maze = b.reshape(10,10)
    output.clear()
    print(maze)
    print("----------------------")
    i = 0
    while i < len(b):
      if b[i] == 0:
        b[i] += 2
      if b[i] == 1:
        if b[i+9] == 0:
          b[i+9] += 2
        if b[i+9] == 1:
          break
        i += 9
      i += 1
    indexes = np.where(b == 2)
    c = indexes[0]
    c = c[len(c)-1]
    j = c
    b[j] = 0
    if b[j+9] == 0:
      b[j+9] += 2
      j += 10
    while j < len(b):
        if b[j] == 0:
          b[j] += 2
        if b[j] == 1:
          if b[j+9] == 0:
            b[j+9] += 2 
          if b[j+9] == 1:
            break
          j += 9
        j += 1
    if b[0] == 2 and b[99] == 2:
      b = b.reshape(10,10)
      print(b)
      break  

  except IndexError:
    output.clear()


[[0. 1. 1. 0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0. 1. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1. 1.]
 [1. 0. 0. 0. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0. 1. 0. 0.]]
----------------------
[[2. 1. 1. 0. 0. 1. 0. 0. 1. 1.]
 [2. 2. 1. 0. 0. 0. 0. 1. 0. 1.]
 [1. 2. 1. 1. 0. 0. 0. 0. 0. 1.]
 [1. 2. 1. 1. 0. 1. 0. 1. 0. 0.]
 [1. 2. 0. 1. 0. 1. 1. 0. 0. 1.]
 [0. 2. 1. 0. 0. 1. 0. 0. 1. 1.]
 [1. 2. 2. 2. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 2. 1. 1. 0. 1. 0. 0.]
 [1. 1. 0. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 0. 1. 0. 0. 0. 1. 0. 2.]]
