<a href="https://colab.research.google.com/github/InowaR/map/blob/main/labyrinth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import numpy as np

def train(X, Y):
  w1 = np.random.random((36,10))
  w2 = np.random.random((10,36))
  for i in range(1000):
    S1 = 1 / (1 + np.exp(-(np.dot(X, w1))))
    S2 = 1 / (1 + np.exp(-(np.dot(S1, w2))))
    S2_delta = (Y - S2) * (S2 * (1 - S2))
    S1_delta = S2_delta.dot(w2.T) * (S1 * (1 - S1))
    w1 += X.T.dot(S1_delta)
    w2 += S1.T.dot(S2_delta)
  return w1, w2

def predict(test, w1, w2):
  S1 = 1 / (1 + np.exp(-(np.dot(test, w1))))
  S2 = 1 / (1 + np.exp(-(np.dot(S1, w2))))
  return S2

def main():
  a = train(X, Y)
  w1, w2 = a
  b = predict(test, w1, w2)
  print(b)

if __name__ == "__main__":
  X = np.array([[0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,1,1,0], [0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0]])
  Y = np.array([[1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1], [1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,1,1,1,1,1,0,0,1]])
  test = np.array([[0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0]])
  main()
  result = np.array([[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,1,1,1,1,1,0,0,1]])
  res = result.reshape(6,6)
  print(res)

[[0.99407175 0.00799916 0.00799736 0.00694212 0.00498386 0.00559686
  0.99542523 0.00517215 0.00611701 0.00583474 0.00769452 0.00506026
  0.99663673 0.03412438 0.03303796 0.00502218 0.006302   0.00556498
  0.96741747 0.00583877 0.03213652 0.00669553 0.00483677 0.00792599
  0.96894321 0.00661101 0.99406759 0.99605809 0.99433407 0.99444398
  0.96605763 0.96846472 0.96873119 0.00631065 0.00535894 0.99442016]]
[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 1 1 1 1]
 [1 1 1 0 0 1]]
