<a href="https://colab.research.google.com/github/InowaR/map/blob/main/labyrinth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np

def train(X, Y):
  w1 = np.random.random((36,10))
  w2 = np.random.random((10,36))
  for i in range(1000):
    S1 = 1 / (1 + np.exp(-(np.dot(X, w1))))
    S2 = 1 / (1 + np.exp(-(np.dot(S1, w2))))
    S2_delta = (Y - S2) * (S2 * (1 - S2))
    S1_delta = S2_delta.dot(w2.T) * (S1 * (1 - S1))
    w1 += X.T.dot(S1_delta)
    w2 += S1.T.dot(S2_delta)
  return w1, w2

def predict(test, w1, w2):
  S1 = 1 / (1 + np.exp(-(np.dot(test, w1))))
  S2 = 1 / (1 + np.exp(-(np.dot(S1, w2))))
  return S2

def main():
  a = train(X, Y)
  w1, w2 = a
  b = predict(test, w1, w2)
  print(b)

if __name__ == "__main__":
  X = np.array([[0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,1,1,0], [0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,1,1,0]])
  Y = np.array([[1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1], [1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,1,1,1,1,1,1,0,0,1]])
  test = np.array([[0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,0,0,0,0,0,1,1,0]])
  print(X[0].reshape(6,6))
  print("-----------------------")
  result = np.array([[1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1]])
  res = result.reshape(6,6)
  print(res)
  print("-----------------------")
  main()

[[0 1 0 0 0 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]
 [0 1 0 1 1 1]
 [1 1 0 0 0 0]
 [0 0 0 1 1 0]]
-----------------------
[[1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 1 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 1 1 1]
 [0 0 0 0 0 1]]
-----------------------
[[0.99684511 0.00393549 0.00391938 0.00432729 0.00401342 0.00479767
  0.99679148 0.00316039 0.00506693 0.00506885 0.00428957 0.0033521
  0.99650876 0.96509921 0.96468415 0.00323944 0.00615259 0.00429257
  0.03485351 0.00387679 0.96497358 0.00473686 0.00490974 0.00441017
  0.0350024  0.00384296 0.9966465  0.99837325 0.99864387 0.99524541
  0.03486303 0.03483581 0.03489022 0.00437044 0.00496034 0.99598109]]
