<a href="https://colab.research.google.com/github/InowaR/map/blob/main/walls.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [310]:
import numpy as np

a = [
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
]

a = np.array(a)
a = a.reshape(10,10)
print(a)
print("-------------------------------------------")

start = 1, 1
end = 2, 5

m = []
for i in range(len(a)):
    m.append([])
    for j in range(len(a[i])):
        m[-1].append(0)
i, j = start
m[i][j] = 1

def make_step(k):
  for i in range(len(m)):
    for j in range(len(m[i])):
      if m[i][j] == k:
        if i>0 and m[i-1][j] == 0 and a[i-1][j] == 0:
          m[i-1][j] = k + 1
        if j>0 and m[i][j-1] == 0 and a[i][j-1] == 0:
          m[i][j-1] = k + 1
        if i<len(m)-1 and m[i+1][j] == 0 and a[i+1][j] == 0:
          m[i+1][j] = k + 1
        if j<len(m[i])-1 and m[i][j+1] == 0 and a[i][j+1] == 0:
           m[i][j+1] = k + 1
k = 0
while m[end[0]][end[1]] == 0:
    k += 1
    make_step(k)

new = np.array(m)
new = new.reshape(10,10)
print(new)
print("-------------------------------------------")

i, j = end
k = m[i][j]
path = [(i,j)]
while k > 1:
  if i > 0 and m[i - 1][j] == k-1:
    i, j = i-1, j
    path.append((i, j))
    k-=1
  elif j > 0 and m[i][j - 1] == k-1:
    i, j = i, j-1
    path.append((i, j))
    k-=1
  elif i < len(m) - 1 and m[i + 1][j] == k-1:
    i, j = i+1, j
    path.append((i, j))
    k-=1
  elif j < len(m[i]) - 1 and m[i][j + 1] == k-1:
    i, j = i, j+1
    path.append((i, j))
    k -= 1

b = np.zeros((10,10))
for i,j in path:
  b[i][j] = 1

print(b)
print("-------------------------------------------")

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 1 0 1 0 0 0 0 1]
 [1 0 1 0 1 0 0 0 0 1]
 [1 0 1 0 1 1 1 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
-------------------------------------------
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0 13  0  0 22 21 20  0]
 [ 0  2  0 12  0 22 21 20 19  0]
 [ 0  3  0 11  0  0  0  0 18  0]
 [ 0  4  0 10 11 12 13  0 17  0]
 [ 0  5  0  9 10 11 12  0 16  0]
 [ 0  6  7  8  9 10 11  0 15  0]
 [ 0  7  0  9 10 11 12 13 14  0]
 [ 0  8  0 10 11 12 13 14 15  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
-------------------------------------------
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
-------------------